/// VIN Decoder Service
/// Provides basic VIN decoding functionality for auto car detection
class VinDecoder {
  static const Map<String, String> _wmiCodes = {
    // World Manufacturer Identifier (WMI) codes
    '1A': 'American Motors',
    '1B': 'BMW',
    '1C': 'Chrysler',
    '1D': 'Dodge',
    '1F': 'Ford',
    '1G': 'General Motors',
    '1H': 'Honda',
    '1J': 'Jeep',
    '1L': 'Lincoln',
    '1M': 'Mercury',
    '1N': 'Nissan',
    '1P': 'Plymouth',
    '1T': 'Toyota',
    '1V': 'Volvo',
    '1Y': 'Mazda',
    '1Z': 'Mitsubishi',
    '2A': 'Audi',
    '2B': 'BMW',
    '2C': 'Chrysler',
    '2D': 'Dodge',
    '2F': 'Ford',
    '2G': 'General Motors',
    '2H': 'Honda',
    '2J': 'Jeep',
    '2L': 'Lincoln',
    '2M': 'Mercury',
    '2N': 'Nissan',
    '2P': 'Plymouth',
    '2T': 'Toyota',
    '2V': 'Volvo',
    '3A': 'Audi',
    '3B': 'BMW',
    '3C': 'Chrysler',
    '3D': 'Dodge',
    '3F': 'Ford',
    '3G': 'General Motors',
    '3H': 'Honda',
    '3J': 'Jeep',
    '3L': 'Lincoln',
    '3M': 'Mercury',
    '3N': 'Nissan',
    '3P': 'Plymouth',
    '3T': 'Toyota',
    '3V': 'Volvo',
    '4A': 'Audi',
    '4B': 'BMW',
    '4C': 'Chrysler',
    '4D': 'Dodge',
    '4F': 'Ford',
    '4G': 'General Motors',
    '4H': 'Honda',
    '4J': 'Jeep',
    '4L': 'Lincoln',
    '4M': 'Mercury',
    '4N': 'Nissan',
    '4P': 'Plymouth',
    '4T': 'Toyota',
    '4V': 'Volvo',
    '5A': 'Audi',
    '5B': 'BMW',
    '5C': 'Chrysler',
    '5D': 'Dodge',
    '5F': 'Ford',
    '5G': 'General Motors',
    '5H': 'Honda',
    '5J': 'Jeep',
    '5L': 'Lincoln',
    '5M': 'Mercury',
    '5N': 'Nissan',
    '5P': 'Plymouth',
    '5T': 'Toyota',
    '5V': 'Volvo',
    'JF': 'Fuji Heavy Industries (Subaru)',
    'JH': 'Honda',
    'JM': 'Mazda',
    'JN': 'Nissan',
    'JT': 'Toyota',
    'KL': 'Kia',
    'KM': 'Hyundai',
    'KN': 'Kia',
    'KMH': 'Hyundai',
    'KMT': 'Hyundai',
    'KNA': 'Kia',
    'KND': 'Kia',
    'KNH': 'Hyundai',
    'KPT': 'Kia',
    'KUN': 'Hyundai',
    'KX1': 'Hyundai',
    'LJ': 'Lexus',
    'LJ1': 'Lexus',
    'LJ2': 'Lexus',
    'LJ3': 'Lexus',
    'LJ4': 'Lexus',
    'LJ5': 'Lexus',
    'LJ6': 'Lexus',
    'LJ7': 'Lexus',
    'LJ8': 'Lexus',
    'LJ9': 'Lexus',
    'LJ0': 'Lexus',
    'LJA': 'Lexus',
    'LJB': 'Lexus',
    'LJC': 'Lexus',
    'LJD': 'Lexus',
    'LJE': 'Lexus',
    'LJF': 'Lexus',
    'LJG': 'Lexus',
    'LJH': 'Lexus',
    'LJI': 'Lexus',
    'LJJ': 'Lexus',
    'LJK': 'Lexus',
    'LJL': 'Lexus',
    'LJM': 'Lexus',
    'LJN': 'Lexus',
    'LJO': 'Lexus',
    'LJP': 'Lexus',
    'LJQ': 'Lexus',
    'LJR': 'Lexus',
    'LJS': 'Lexus',
    'LJT': 'Lexus',
    'LJU': 'Lexus',
    'LJV': 'Lexus',
    'LJW': 'Lexus',
    'LJX': 'Lexus',
    'LJY': 'Lexus',
    'LJZ': 'Lexus',
    'LS': 'Lexus',
    'LS0': 'Lexus',
    'LS1': 'Lexus',
    'LS2': 'Lexus',
    'LS3': 'Lexus',
    'LS4': 'Lexus',
    'LS5': 'Lexus',
    'LS6': 'Lexus',
    'LS7': 'Lexus',
    'LS8': 'Lexus',
    'LS9': 'Lexus',
    'LSA': 'Lexus',
    'LSB': 'Lexus',
    'LSC': 'Lexus',
    'LSD': 'Lexus',
    'LSE': 'Lexus',
    'LSF': 'Lexus',
    'LSG': 'Lexus',
    'LSH': 'Lexus',
    'LSI': 'Lexus',
    'LSJ': 'Lexus',
    'LSK': 'Lexus',
    'LSL': 'Lexus',
    'LSM': 'Lexus',
    'LSN': 'Lexus',
    'LSO': 'Lexus',
    'LSP': 'Lexus',
    'LSQ': 'Lexus',
    'LSR': 'Lexus',
    'LSS': 'Lexus',
    'LST': 'Lexus',
    'LSU': 'Lexus',
    'LSV': 'Lexus',
    'LSW': 'Lexus',
    'LSX': 'Lexus',
    'LSY': 'Lexus',
    'LSZ': 'Lexus',
    'LV': 'Lexus',
    'LV0': 'Lexus',
    'LV1': 'Lexus',
    'LV2': 'Lexus',
    'LV3': 'Lexus',
    'LV4': 'Lexus',
    'LV5': 'Lexus',
    'LV6': 'Lexus',
    'LV7': 'Lexus',
    'LV8': 'Lexus',
    'LV9': 'Lexus',
    'LVA': 'Lexus',
    'LVB': 'Lexus',
    'LVC': 'Lexus',
    'LVD': 'Lexus',
    'LVE': 'Lexus',
    'LVF': 'Lexus',
    'LVG': 'Lexus',
    'LVH': 'Lexus',
    'LVI': 'Lexus',
    'LVJ': 'Lexus',
    'LVK': 'Lexus',
    'LVL': 'Lexus',
    'LVM': 'Lexus',
    'LVN': 'Lexus',
    'LVO': 'Lexus',
    'LVP': 'Lexus',
    'LVQ': 'Lexus',
    'LVR': 'Lexus',
    'LVS': 'Lexus',
    'LVT': 'Lexus',
    'LVU': 'Lexus',
    'LVV': 'Lexus',
    'LVW': 'Lexus',
    'LVX': 'Lexus',
    'LVY': 'Lexus',
    'LVZ': 'Lexus',
    'WAU': 'Audi',
    'WBA': 'BMW',
    'WBS': 'BMW',
    'WBY': 'BMW',
    'WDB': 'Mercedes-Benz',
    'WDC': 'Mercedes-Benz',
    'WDD': 'Mercedes-Benz',
    'WDF': 'Mercedes-Benz',
    'WDG': 'Mercedes-Benz',
    'WDH': 'Mercedes-Benz',
    'WDJ': 'Mercedes-Benz',
    'WDL': 'Mercedes-Benz',
    'WDM': 'Mercedes-Benz',
    'WDN': 'Mercedes-Benz',
    'WDP': 'Mercedes-Benz',
    'WDQ': 'Mercedes-Benz',
    'WDR': 'Mercedes-Benz',
    'WDS': 'Mercedes-Benz',
    'WDT': 'Mercedes-Benz',
    'WDU': 'Mercedes-Benz',
    'WDV': 'Mercedes-Benz',
    'WDW': 'Mercedes-Benz',
    'WDX': 'Mercedes-Benz',
    'WDY': 'Mercedes-Benz',
    'WDZ': 'Mercedes-Benz',
    'WVG': 'Volkswagen',
    'WVW': 'Volkswagen',
    'WV1': 'Volkswagen',
    'WV2': 'Volkswagen',
    'WV3': 'Volkswagen',
    'WV4': 'Volkswagen',
    'WV5': 'Volkswagen',
    'WV6': 'Volkswagen',
    'WV7': 'Volkswagen',
    'WV8': 'Volkswagen',
    'WV9': 'Volkswagen',
    'WVA': 'Volkswagen',
    'WVB': 'Volkswagen',
    'WVC': 'Volkswagen',
    'WVD': 'Volkswagen',
    'WVE': 'Volkswagen',
    'WVF': 'Volkswagen',
    'WVH': 'Volkswagen',
    'WVI': 'Volkswagen',
    'WVJ': 'Volkswagen',
    'WVK': 'Volkswagen',
    'WVL': 'Volkswagen',
    'WVM': 'Volkswagen',
    'WVN': 'Volkswagen',
    'WVO': 'Volkswagen',
    'WVP': 'Volkswagen',
    'WVQ': 'Volkswagen',
    'WVR': 'Volkswagen',
    'WVS': 'Volkswagen',
    'WVT': 'Volkswagen',
    'WVU': 'Volkswagen',
    'WVV': 'Volkswagen',
    'WVX': 'Volkswagen',
    'WVY': 'Volkswagen',
    'WVZ': 'Volkswagen',
    'XTA': 'Lada',
    'XTB': 'Lada',
    'XTC': 'Lada',
    'XTD': 'Lada',
    'XTE': 'Lada',
    'XTF': 'Lada',
    'XTG': 'Lada',
    'XTH': 'Lada',
    'XTI': 'Lada',
    'XTJ': 'Lada',
    'XTK': 'Lada',
    'XTL': 'Lada',
    'XTM': 'Lada',
    'XTN': 'Lada',
    'XTO': 'Lada',
    'XTP': 'Lada',
    'XTQ': 'Lada',
    'XTR': 'Lada',
    'XTS': 'Lada',
    'XTT': 'Lada',
    'XTU': 'Lada',
    'XTV': 'Lada',
    'XTW': 'Lada',
    'XTX': 'Lada',
    'XTY': 'Lada',
    'XTZ': 'Lada',
    'YV1': 'Volvo',
    'YV2': 'Volvo',
    'YV3': 'Volvo',
    'YV4': 'Volvo',
    'YV5': 'Volvo',
    'YV6': 'Volvo',
    'YV7': 'Volvo',
    'YV8': 'Volvo',
    'YV9': 'Volvo',
    'YVA': 'Volvo',
    'YVB': 'Volvo',
    'YVC': 'Volvo',
    'YVD': 'Volvo',
    'YVE': 'Volvo',
    'YVF': 'Volvo',
    'YVG': 'Volvo',
    'YVH': 'Volvo',
    'YVI': 'Volvo',
    'YVJ': 'Volvo',
    'YVK': 'Volvo',
    'YVL': 'Volvo',
    'YVM': 'Volvo',
    'YVN': 'Volvo',
    'YVO': 'Volvo',
    'YVP': 'Volvo',
    'YVQ': 'Volvo',
    'YVR': 'Volvo',
    'YVS': 'Volvo',
    'YVT': 'Volvo',
    'YVU': 'Volvo',
    'YVV': 'Volvo',
    'YVW': 'Volvo',
    'YVX': 'Volvo',
    'YVY': 'Volvo',
    'YVZ': 'Volvo',
    'ZF1': 'Ferrari',
    'ZF2': 'Ferrari',
    'ZF3': 'Ferrari',
    'ZF4': 'Ferrari',
    'ZF5': 'Ferrari',
    'ZF6': 'Ferrari',
    'ZF7': 'Ferrari',
    'ZF8': 'Ferrari',
    'ZF9': 'Ferrari',
    'ZFA': 'Ferrari',
    'ZFB': 'Ferrari',
    'ZFC': 'Ferrari',
    'ZFD': 'Ferrari',
    'ZFE': 'Ferrari',
    'ZFF': 'Ferrari',
    'ZFG': 'Ferrari',
    'ZFH': 'Ferrari',
    'ZFI': 'Ferrari',
    'ZFJ': 'Ferrari',
    'ZFK': 'Ferrari',
    'ZFL': 'Ferrari',
    'ZFM': 'Ferrari',
    'ZFN': 'Ferrari',
    'ZFO': 'Ferrari',
    'ZFP': 'Ferrari',
    'ZFR': 'Ferrari',
    'ZFS': 'Ferrari',
    'ZFT': 'Ferrari',
    'ZFU': 'Ferrari',
    'ZFV': 'Ferrari',
    'ZFW': 'Ferrari',
    'ZFX': 'Ferrari',
    'ZFY': 'Ferrari',
    'ZFZ': 'Ferrari',
  };

  static VinInfo decodeVin(String vin) {
    if (vin.length != 17) {
      return VinInfo(
        vin: vin,
        manufacturer: 'Unknown',
        brand: 'Unknown',
        model: 'Unknown',
        year: null,
        isValid: false,
      );
    }

    final normalizedVin = vin.toUpperCase().replaceAll(' ', '');
    final wmi = normalizedVin.substring(0, 3);
    final yearCode = normalizedVin[9];
    
    final manufacturer = _wmiCodes[wmi] ?? 'Unknown';
    final brand = _extractBrand(manufacturer);
    final year = _decodeYear(yearCode);
    
    return VinInfo(
      vin: normalizedVin,
      manufacturer: manufacturer,
      brand: brand,
      model: 'Unknown', // Would need more comprehensive database for model detection
      year: year,
      isValid: true,
    );
  }

  static String _extractBrand(String manufacturer) {
    // Extract common brand names from manufacturer names
    if (manufacturer.toLowerCase().contains('toyota')) return 'Toyota';
    if (manufacturer.toLowerCase().contains('honda')) return 'Honda';
    if (manufacturer.toLowerCase().contains('nissan')) return 'Nissan';
    if (manufacturer.toLowerCase().contains('mazda')) return 'Mazda';
    if (manufacturer.toLowerCase().contains('mitsubishi')) return 'Mitsubishi';
    if (manufacturer.toLowerCase().contains('subaru')) return 'Subaru';
    if (manufacturer.toLowerCase().contains('bmw')) return 'BMW';
    if (manufacturer.toLowerCase().contains('mercedes')) return 'Mercedes-Benz';
    if (manufacturer.toLowerCase().contains('audi')) return 'Audi';
    if (manufacturer.toLowerCase().contains('volkswagen')) return 'Volkswagen';
    if (manufacturer.toLowerCase().contains('volvo')) return 'Volvo';
    if (manufacturer.toLowerCase().contains('ford')) return 'Ford';
    if (manufacturer.toLowerCase().contains('general motors')) return 'GM';
    if (manufacturer.toLowerCase().contains('chrysler')) return 'Chrysler';
    if (manufacturer.toLowerCase().contains('dodge')) return 'Dodge';
    if (manufacturer.toLowerCase().contains('jeep')) return 'Jeep';
    if (manufacturer.toLowerCase().contains('lexus')) return 'Lexus';
    if (manufacturer.toLowerCase().contains('hyundai')) return 'Hyundai';
    if (manufacturer.toLowerCase().contains('kia')) return 'Kia';
    if (manufacturer.toLowerCase().contains('lada')) return 'Lada';
    if (manufacturer.toLowerCase().contains('ferrari')) return 'Ferrari';
    
    return manufacturer;
  }

  static int? _decodeYear(String yearCode) {
    const Map<String, int> yearCodes = {
      'A': 2010, 'B': 2011, 'C': 2012, 'D': 2013, 'E': 2014, 'F': 2015, 'G': 2016, 'H': 2017,
      'J': 2018, 'K': 2019, 'L': 2020, 'M': 2021, 'N': 2022, 'P': 2023, 'R': 2024, 'S': 2025,
      'T': 2026, 'V': 2027, 'W': 2028, 'X': 2029, 'Y': 2030, '1': 2031, '2': 2032, '3': 2033,
      '4': 2034, '5': 2035, '6': 2036, '7': 2037, '8': 2038, '9': 2039,
      // 1980-1989 codes
      'a': 1980, 'b': 1981, 'c': 1982, 'd': 1983, 'e': 1984, 'f': 1985, 'g': 1986, 'h': 1987,
      'j': 1988, 'k': 1989,
    };
    
    return yearCodes[yearCode];
  }
}

class VinInfo {
  final String vin;
  final String manufacturer;
  final String brand;
  final String model;
  final int? year;
  final bool isValid;

  const VinInfo({
    required this.vin,
    required this.manufacturer,
    required this.brand,
    required this.model,
    required this.year,
    required this.isValid,
  });

  @override
  String toString() {
    return 'VinInfo(vin: $vin, manufacturer: $manufacturer, brand: $brand, model: $model, year: $year, isValid: $isValid)';
  }
}
